-- Users table seeds here (Example)
-- INSERT INTO users (id, name, password) VALUES (1, 'Alice Lang', 'password');

INSERT INTO "users" (id,name,password) VALUES (1,'Sasha Hicks','password'),(2,'Yetta Berg','password'),(3,'Michelle Wooten','password'),(4,'Karyn Mcdowell','password'),(5,'Winter Meyers','password'),(6,'Stacey Morgan','password'),(7,'Sacha Bowen','password'),(8,'Maile Gardner','password'),(9,'Wanda Gutierrez','password'),(10,'Kelly Woodard','password');
INSERT INTO "users" (id,name,password) VALUES (11,'Ava Velasquez','password'),(12,'Alea Swanson','password'),(13,'Sage Gates','password'),(14,'Imelda Leach','password'),(15,'Patricia Hyde','password'),(16,'Aretha Snyder','password'),(17,'Camille Strong','password'),(18,'Mia Palmer','password'),(19,'Brenda Watts','password'),(20,'Britanney Wilkerson','password');
INSERT INTO "users" (id,name,password) VALUES (21,'Eden Frederick','password'),(22,'Kellie Barton','password'),(23,'Taylor Franklin','password'),(24,'Clare Morris','password'),(25,'Sarah Goff','password'),(26,'Emerald Nichols','password'),(27,'Leilani Sweeney','password'),(28,'Inez Macdonald','password'),(29,'Inga Hull','password'),(30,'Olympia Saunders','password');
INSERT INTO "users" (id,name,password) VALUES (31,'Brenda Hill','password'),(32,'Alisa Harding','password'),(33,'Ima Dillon','password'),(34,'Mallory Burgess','password'),(35,'Frances Hampton','password'),(36,'Myra Skinner','password'),(37,'Tara Mayer','password'),(38,'Kelly Barlow','password'),(39,'Iris Vaughn','password'),(40,'Macy Henson','password');
INSERT INTO "users" (id,name,password) VALUES (41,'Gay Haney','password'),(42,'Tatiana Mckinney','password'),(43,'Gloria Donovan','password'),(44,'Alexa Good','password'),(45,'Gemma Sims','password'),(46,'Medge Ball','password'),(47,'Melinda Mayer','password'),(48,'Idona Frye','password'),(49,'Fiona Wood','password'),(50,'Gretchen Burgess','password');
INSERT INTO "users" (id,name,password) VALUES (51,'Hilary Thomas','password'),(52,'Lillian Castillo','password'),(53,'Frances Hamilton','password'),(54,'Rina Hart','password'),(55,'Julie Pollard','password'),(56,'Xena Patrick','password'),(57,'Orla Puckett','password'),(58,'Debra Macdonald','password'),(59,'Jennifer Joyner','password'),(60,'Candice Joyce','password');
INSERT INTO "users" (id,name,password) VALUES (61,'Sasha Nicholson','password'),(62,'Bryar Mcintyre','password'),(63,'Yeo Goodwin','password'),(64,'Sheila Floyd','password'),(65,'Mia Solis','password'),(66,'Margaret Mcconnell','password'),(67,'Genevieve Fuller','password'),(68,'Harriet Ford','password'),(69,'Caryn Pugh','password'),(70,'Hyacinth Rivers','password');
INSERT INTO "users" (id,name,password) VALUES (71,'Sage Perry','password'),(72,'Hanae Burch','password'),(73,'Portia Horton','password'),(74,'Wynter Rowland','password'),(75,'Rebekah Sanders','password'),(76,'Emily Baldwin','password'),(77,'Rowan Bruce','password'),(78,'Hedwig Maldonado','password'),(79,'Kyra Bradley','password'),(80,'Madonna Marshall','password');
INSERT INTO "users" (id,name,password) VALUES (81,'Tana Kinney','password'),(82,'Leah Holt','password'),(83,'Xantha Kelly','password'),(84,'Quintessa Ayers','password'),(85,'September Cantrell','password'),(86,'Holly Gibbs','password'),(87,'Jordan Padilla','password'),(88,'Kaitlin Mcclure','password'),(89,'Rinah Camacho','password'),(90,'Nicole Barlow','password');
INSERT INTO "users" (id,name,password) VALUES (91,'Quintessa Campos','password'),(92,'Mallory Keith','password'),(93,'Mona Brooks','password'),(94,'Serena Frazier','password'),(95,'Chelsea Medina','password'),(96,'Noelani Holland','password'),(97,'Rama Kennedy','password'),(98,'Tashya Howe','password'),(99,'Kaye Gray','password'),(100,'Shellie Haney','password');
