-- Users table seeds here (Example)
-- INSERT INTO users (id, name, password) VALUES (1, 'Alice Lang', 'password');

INSERT INTO "users" (name,password) VALUES ('Blake Bonner','password'),('Dorian Dixon','password'),('Paul Odom','password'),('Haviva Church','password'),('Yvette Dudley','password'),('Dominic Hopkins','password'),('Wesley Spencer','password'),('Orli Contreras','password'),('Zeus Leon','password'),('Hedy Morton','password');
INSERT INTO "users" (name,password) VALUES ('Clayton Hyde','password'),('Guinevere Humphrey','password'),('Lyle Macdonald','password'),('Madaline Acosta','password'),('Germane Frye','password'),('Shay Terry','password'),('Melodie Wynn','password'),('Nadine Abbott','password'),('Regina Herrera','password'),('Gwendolyn Higgins','password');
INSERT INTO "users" (name,password) VALUES ('Quemby Crawford','password'),('Uriah Lindsey','password'),('Melodie Wilder','password'),('Rudyard Suarez','password'),('Knox Craft','password'),('Alvin Baker','password'),('Ramona Henderson','password'),('Nina Forbes','password'),('Glenna Wiggins','password'),('Urielle Frye','password');
INSERT INTO "users" (name,password) VALUES ('Giacomo Norton','password'),('Xandra Velez','password'),('Tana Galloway','password'),('Brittany Baxter','password'),('Adam Fernandez','password'),('Donovan Newman','password'),('Robert Roberts','password'),('Mercedes Marsh','password'),('Kristen Curtis','password'),('Celeste Beasley','password');
INSERT INTO "users" (name,password) VALUES ('Karina Mcknight','password'),('Paul Holt','password'),('Hyatt Crosby','password'),('Ignatius Gilmore','password'),('Hiroko Faulkner','password'),('Melvin Rivas','password'),('Maite Reid','password'),('Ulysses Morris','password'),('Damian Mccall','password'),('Austin Winters','password');
INSERT INTO "users" (name,password) VALUES ('Nerea Melendez','password'),('Walter Wise','password'),('Courtney Salazar','password'),('Nathaniel Holder','password'),('Scarlet Hinton','password'),('Preston Washington','password'),('Madison Zimmerman','password'),('Garrison Briggs','password'),('Jaden Welch','password'),('Clinton Klein','password');
INSERT INTO "users" (name,password) VALUES ('Raymond Mcpherson','password'),('Imani Walton','password'),('Erasmus Moss','password'),('Ila Carroll','password'),('Ramona Savage','password'),('Britanni Reese','password'),('Shafira Booth','password'),('Finn James','password'),('Oscar Montgomery','password'),('Sarah Lawson','password');
INSERT INTO "users" (name,password) VALUES ('Kristen Santana','password'),('Giacomo Mclean','password'),('Mechelle Hernandez','password'),('Alana Gallegos','password'),('Irene Parker','password'),('Madeline Merritt','password'),('Dawn Powers','password'),('Lars Washington','password'),('Xerxes Wilkerson','password'),('Raven Leach','password');
INSERT INTO "users" (name,password) VALUES ('April Austin','password'),('Bryar Bean','password'),('Helen Potter','password'),('Mikayla Schultz','password'),('Edan Stanton','password'),('Edan Holt','password'),('Kevin Cole','password'),('Leonard Reed','password'),('Arthur Hooper','password'),('Nita Day','password');
INSERT INTO "users" (name,password) VALUES ('Stuart Mann','password'),('Patricia Caldwell','password'),('Shoshana Tucker','password'),('Kelly Moses','password'),('Emerson Tanner','password'),('Rooney Short','password'),('Sonia White','password'),('Mary Levy','password'),('Basil Gilmore','password'),('Cade Parsons','password');

